import random

# Hardcoded list of names
names = [
    "D. Venkata Tirupathi Rao",
    "M. Kavya",
    "K. Naga Aparna",
    "M. Vyshnavi",
    "M. Harshitha",
    "N. Venkateswara Rao",
    "N. Guna Sri Durgapriya",
    "Shaik Naik Rajak",
    "S. Rajesh",
    "Sk. Ashraf Ali",
    "Sk. Mehar Nigar",
    "Sk. Taslim",
    "SD. Darshan Sultana",
    "N. Vijaya Lakshmi",
    "T. Ranjith Kumar",
    "K. Mani Shankar",
    "C. Pallavi",
    "K. Poojitha",
    "N. Siva",
    "D. Siva Kotireddy",
    "P. Najeer Khan",
    "Y. Gopi Chand",
    "M. Mani Ganesh",
    "V. Gayathri",
    "K. Akhila",
    "S. Mounika",
    "A.L.V. Swapna",
    "B. Kavya",
    "B. Koteswaramma",
    "B. Asha",
    "B. Aparna",
    "D. Nagasai",
    "G. Jagadeeswari",
    "I. Ajor Kumar",
    "J. Sindhura",
    "K. Ruchitha",
    "K. Sailaja",
    "K. Kasthuri",
    "M. Rathnakumari",
    "P. Jayasimha",
    "Renusree Pattem",
    "P. Prasanna",
    "Puli Amulya",
    "P. Thanuja",
    "R. Ranjith Kumar",
    "Shaik Basheerun",
    "S. Moinuddin Ahmed",
    "S. Bala Bhavadeep Reddy",
    "T. Harika",
    "Tallapalli Prasanna",
    "T. Anand Kishore",
    "V. Praveen",
    "V. Narendra",
    "Y. Dinesh",
    "Y. Meghana Sree",
    "P. Monasri",
    "K. Ahalya",
    "P. Mahesh Babu",
    "SK. Mastan Shareef",
    "Boma Nagasai Akhil",
    "CH. Venkata Lokesh",
    "D. Dhanush",
    "G. Vishnu",
    "K. Yagnesh",
    "K. Chatrish Chowdary",
    "Raja Vardhan",
    "N. Kesavi Priya",
    "SK. Anas",
    "T. Nikitha",
    "T. Yamini",
    "V. Venkata Sai Tejesh",
    "I. Praveen Kumar",
    "R. Prathyusha",
    "J. Ravi Teja",
    "SK. Varfan",
    "Cho Adi Lakshmi",
    "Ch. Jasmitha",
    "Ch. Jashpujitha",
    "Sd. Mohammed Rafi",
    "Sd. Hameed",
    "G. Gnana Deepu",
    "G. Sivaiah",
    "N. Fathimabi",
    "SK. Maneesha",
    "SK. Rizwana",
    "L. Kavya",
    "R. Sneha",
    "Sk. Samreen",
    "P. Bhavani",
    "Ch. Manasa",
    "P. Harika",
    "Ch. Anil Kumar",
    "G. Siva Sankar",
    "G. Srinadh",
    "Sai N",
    "N Vishnu",
    "D. Sirisha",
    "G. Yasaswi",
    "D. Deepthi",
    "B. Srilakshmi",
    "J. Neelima",
    "G. Kavitha",
    "G.V.S. Likhithe",
    "G. Lasya",
    "K. Roja",
    "P. Chakravarthi",
    "Swaroop"
]

# Pick a random name
selected_name = random.choice(names)

print("Selected Name:", selected_name)